### ISSUE TITLE
Database Setup

### ISSUE THREAD

**Issue by mittrab** [thecryptoundertaker/discord-tip-bot#11]
# Summary

Need a place to store state. The primary need is store a mapping of discord usernames the associated wallet private 
keys.

Keys should be stored encrypted with a master key using pynacl.

# tasks

- [x] Add PyNaCl to requirements.txt
- [x] add db path to config
- [x] create and store a secret master key
- [x] create db function
- [x] create tables if not exist functions
- [x] draft initial schema
- [x] create save user function that handles encrypted fields

## Questions

- [ ] use sqlalchemy or just straight sqlite?
- [ ] ANSW or pysqlite?
- [ ] best way to handle an encrypted field?
