### ISSUE TITLE
Config Management

### ISSUE THREAD

**Issue by mittrab** [thecryptoundertaker/discord-tip-bot#2]
Setup a config file to store all config variables such as RPC address, provider type, wallet address, etc

For flexibility and deployment purposes, it should:
1. check environment variables
2. check local config files
3. use defaults

## Tasks

- [x]  Pull in pydotenv
- [x] create initial config.py in top level dir
  - fantom node address
  - provider type (wss, rpc, etc)
  - later this will contain things like botname, rooms to join etc,
- [x]  pull in secrets from envfile and environment
- [x] setup default config
- [x] setup development config
- [x] setup production config

## config keys

- [ ] fantom API addr and scheme
- [ ] default token
- [ ] default tip amount
- [ ] discord API key
- [ ] default tax amount
- [ ] DB path
- [ ] master encrypt key
- [ ] 

## Questions
- [x] .yaml or .ini or .py?
  - use py. YAML sucks, and .ini is ugly.
- [x] 3rd party lib to manage local env?
  - use dotenv
- [ ] Manage secrets(wallet key, discord API key)

## References

- https://github.com/theskumar/python-dotenv
- https://wiki.python.org/moin/ConfigParserExamples
- https://pyyaml.org/wiki/PyYAMLDocumentation
